import { account, isAppwriteConfigured } from "./client";
import type { UserProfile } from "@/types/settings";

export interface AppwriteUser {
  $id: string;
  name: string;
  email: string;
}

/**
 * Build the Appwrite OAuth URL for Google sign-in.
 * The success/failure URLs point to the local callback server.
 *
 * @param callbackPort - The port the local OAuth callback TCP server is listening on.
 * @param state - A cryptographic nonce generated by the caller. Embedded in the
 *   success redirect URL so it's returned in the callback and can be validated
 *   against the value stored in sessionStorage to prevent CSRF.
 */
export function getOAuthUrl(callbackPort: number, state: string): string {
  const successUrl = `http://localhost:${callbackPort}/callback?provider=appwrite&state=${encodeURIComponent(state)}`;
  const failureUrl = `http://localhost:${callbackPort}/callback?error=oauth_failed`;

  // The SDK's createOAuth2Token does a browser redirect.
  // For Tauri, we build the URL manually so we can open it in the system browser.
  const endpoint = import.meta.env.VITE_APPWRITE_ENDPOINT || "https://cloud.appwrite.io/v1";
  const projectId = import.meta.env.VITE_APPWRITE_PROJECT_ID || "";

  return (
    `${endpoint}/account/tokens/oauth2/google` +
    `?project=${encodeURIComponent(projectId)}` +
    `&success=${encodeURIComponent(successUrl)}` +
    `&failure=${encodeURIComponent(failureUrl)}` +
    `&scopes[]=${encodeURIComponent("openid")}` +
    `&scopes[]=${encodeURIComponent("email")}` +
    `&scopes[]=${encodeURIComponent("profile")}`
  );
}

/**
 * Exchange the userId + secret from the OAuth callback for an Appwrite session.
 */
export async function createSessionFromOAuth(
  userId: string,
  secret: string
): Promise<AppwriteUser> {
  await account.createSession(userId, secret);
  return account.get();
}

/**
 * Check if there's an active Appwrite session.
 * Returns the user if active, null otherwise.
 */
export async function getActiveSession(): Promise<AppwriteUser | null> {
  if (!isAppwriteConfigured()) return null;
  try {
    return await account.get();
  } catch {
    return null;
  }
}

/**
 * Log out from Appwrite (delete current session).
 */
export async function logout(): Promise<void> {
  try {
    await account.deleteSession("current");
  } catch {
    // Session may already be expired
  }
}

import { syncUserProfile } from "./sync-profiles";

/**
 * Convert Appwrite user to the local UserProfile format and sync to Appwrite DB.
 */
export async function resolveUserProfile(
  awUser: AppwriteUser,
  plan?: string
): Promise<UserProfile> {
  const profile: UserProfile = {
    id: awUser.$id,
    email: awUser.email,
    name: awUser.name,
    plan: (plan as UserProfile["plan"]) || "starter",
  };

  // Sync profile to Appwrite user_profiles collection (upsert)
  try {
    await syncUserProfile(profile);
  } catch (e) {
    console.warn("[Appwrite] Failed to sync user profile:", e);
  }

  return profile;
}
